services:
  test-db:
    image: postgres:15-alpine
    container_name: chirp-test-db
    ports:
      - '${DB_PORT:-5433}:5432'
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-chirp_test}
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 5

  test-app:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
      - DB_HOST=test-db
      - DB_PORT=5432
    depends_on:
      test-db:
        condition: service_healthy
    command: npm test
